version: 2.1

# reusable blocks
defaults: &defaults
  docker:
    - image: circleci/node:12.13

  working_directory: ~/project

# jobs
jobs:
  install_dependencies:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - src
            - .prettierrc
            - .prettierignore
            - package.json
            - tsconfig.build.json
            - tsconfig.json
            - yarn.lock
            - tslint.json

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run: yarn lint

  prettier:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run: yarn prettier:check

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run: yarn test

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run: yarn build

# workflow
workflows:
  version: 2

  build_lint_and_test:
    jobs:
      - install_dependencies

      - lint:
          requires:
            - install_dependencies

      - test:
          requires:
            - install_dependencies

      - prettier:
          requires:
            - install_dependencies

      - build:
          requires:
            - lint
            - test
            - prettier
